"""Blind annotations of the first 20 ARN items.

Produced WITHOUT knowing which passage is the query, which is the analogue,
which is the distractor, or which answer is correct. Each passage was annotated
alone and on its own terms -- deliberately not compared with its neighbours,
because annotating one narrative while looking at another is how a structure
gets bent toward a match.

Vocabulary: INCREASES / DECREASES, the declared family in relalgebra.py. The
annotation records the CAUSAL SKELETON, not the topic -- which is the whole
point of the measure being tested.

Four passages appear in more than one item (the benchmark reuses narratives).
They are annotated identically, which is both correct and a consistency check
on the annotator: divergent annotations of identical text would mean the
process is noise.
"""

A = {
 # -- item block 0 --
 "bfa7818183ad573c": [("isolation", "doubt", "INCREASES"),
                      ("crisis", "mutual_aid", "INCREASES"),
                      ("mutual_aid", "isolation", "DECREASES")],
 "85bc57885e3bfde4": [("disaster", "loss", "INCREASES"),
                      ("loss", "irreversibility", "INCREASES"),
                      ("irreversibility", "dwelling", "DECREASES"),
                      ("dwelling", "action", "DECREASES")],
 "b5059cced19f7396": [("failure", "distress", "INCREASES"),
                      ("distress", "dwelling", "INCREASES"),
                      ("failure", "irreversibility", "INCREASES"),
                      ("irreversibility", "dwelling", "DECREASES")],
 # -- 1 --
 "99ff51f3f0a4e281": [("time", "growth", "INCREASES"),
                      ("growth", "size", "INCREASES"),
                      ("growth", "resemblance_to_origin", "DECREASES")],
 "8296921b0ea18f14": [("effort", "completed_tasks", "INCREASES"),
                      ("completed_tasks", "standing", "INCREASES"),
                      ("standing", "access", "INCREASES"),
                      ("access", "earnings", "INCREASES")],
 "c371b7a227bc9344": [("diligence", "access", "INCREASES"),
                      ("access", "standing", "INCREASES"),
                      ("standing", "advantage_over_peers", "INCREASES")],
 # -- 2 --
 "425cddc63dae4f93": [("distance", "illusion", "INCREASES"),
                      ("illusion", "apparent_value", "INCREASES"),
                      ("illusion", "accuracy", "DECREASES")],
 "3a1d1572416bd403": [("adversity", "distress", "INCREASES"),
                      ("time", "remembered_distress", "DECREASES"),
                      ("remembered_distress", "fondness", "DECREASES")],
 "60427d9e8d35825b": [("hardship", "shared_experience", "INCREASES"),
                      ("shared_experience", "bonding", "INCREASES"),
                      ("bonding", "isolation", "DECREASES")],
 # -- 3 --
 "0dcf509771d4ef22": [("haste", "knowledge_of_partner", "DECREASES"),
                      ("knowledge_of_partner", "mismatch", "DECREASES"),
                      ("mismatch", "regret", "INCREASES"),
                      ("regret", "separation", "INCREASES")],
 "ab9a94b984cfd313": [("warning", "evidence", "INCREASES"),
                      ("dismissal", "evidence", "DECREASES"),
                      ("dismissal", "risk", "INCREASES")],
 "0607a0f1553b9598": [("haste", "volume", "INCREASES"),
                      ("haste", "quality", "DECREASES"),
                      ("quality", "rejection", "DECREASES"),
                      ("rejection", "earnings", "DECREASES")],
 # -- 4 --
 "fe9c5c32c30f679a": [("outward_service", "home_attention", "DECREASES"),
                      ("home_attention", "children_outcome", "INCREASES")],
 "fa48ecd700ad6521": [("inconsistency", "doubt", "INCREASES"),
                      ("doubt", "inherited_belief", "DECREASES"),
                      ("doubt", "new_commitment", "INCREASES")],
 "a6035e3ba7b2e7bd": [("outward_spending", "domestic_provision", "DECREASES"),
                      ("domestic_provision", "standing", "INCREASES")],
 # -- 5 --
 "c1e266f3ed6835c3": [("haste", "knowledge", "DECREASES"),
                      ("warning", "caution", "INCREASES"),
                      ("dismissal", "caution", "DECREASES"),
                      ("knowledge", "conflict", "DECREASES")],
 "7740060989584621": [("haste", "quality", "DECREASES"),
                      ("quality", "remedial_work", "DECREASES"),
                      ("remedial_work", "total_time", "INCREASES")],
 "953292cc8da6d757": [("delay", "credibility", "DECREASES"),
                      ("credibility", "extension", "INCREASES"),
                      ("extension", "completion", "INCREASES")],
 # -- 6 --
 "047fe80d0de750c6": [("first_generation", "pressure", "INCREASES"),
                      ("pressure", "determination", "INCREASES"),
                      ("determination", "effort", "INCREASES")],
 "7fe80cdd47fe4253": [("distraction", "focus", "DECREASES"),
                      ("persistence", "focus", "INCREASES"),
                      ("focus", "achievement", "INCREASES"),
                      ("achievement", "leisure", "INCREASES")],
 "6d09f71a3c4a81f4": [("practice", "flaw_detected", "INCREASES"),
                      ("flaw_detected", "correction", "INCREASES"),
                      ("correction", "performance", "INCREASES"),
                      ("performance", "winning", "INCREASES")],
 # -- 7 --
 "c0508d858652f674": [("age_gap", "embarrassment", "INCREASES"),
                      ("embarrassment", "persistence", "DECREASES"),
                      ("persistence", "growth", "INCREASES"),
                      ("growth", "pride", "INCREASES")],
 "b0fdd26b8323b4f5": [("adversity", "persistence", "DECREASES"),
                      ("fortitude", "persistence", "INCREASES"),
                      ("persistence", "achievement", "INCREASES"),
                      ("achievement", "standing", "INCREASES")],
 "f944512bc74646bf": [("continued_study", "capability", "INCREASES"),
                      ("capability", "certification", "INCREASES"),
                      ("certification", "ambition", "INCREASES")],
 # -- 8 --  (60dd... is the same narrative as 85bc..., annotated identically)
 "60dd233603aadc45": [("disaster", "loss", "INCREASES"),
                      ("loss", "irreversibility", "INCREASES"),
                      ("irreversibility", "dwelling", "DECREASES"),
                      ("dwelling", "action", "DECREASES")],
 "1ae51dafa90a0493": [("failure", "distress", "INCREASES"),
                      ("distress", "dwelling", "INCREASES"),
                      ("acceptance", "dwelling", "DECREASES")],
 "47aef2b71320a8ba": [("neglect", "preparation", "DECREASES"),
                      ("preparation", "failure", "DECREASES"),
                      ("failure", "blame", "INCREASES"),
                      ("blame", "self_correction", "DECREASES")],
 # -- 9 --
 "8ea4e22bb1bbee53": [("freedom", "partying", "INCREASES"),
                      ("partying", "rest", "DECREASES"),
                      ("rest", "focus", "INCREASES"),
                      ("focus", "grades", "INCREASES")],
 "6ef8fe74b25ea439": [("persistence", "approval_rate", "INCREASES"),
                      ("approval_rate", "earnings", "INCREASES"),
                      ("earnings", "hope", "INCREASES")],
 "da7a72f196fbd3d0": [("goal", "anticipation", "INCREASES"),
                      ("obstacle", "hardship", "INCREASES"),
                      ("hardship", "future_relief", "INCREASES")],
 # -- 10 --
 "4d3f1fc138b37dfe": [("prior_failures", "readiness", "INCREASES"),
                      ("readiness", "right_match", "INCREASES"),
                      ("right_match", "commitment", "INCREASES")],
 "fc9ccac9a1f07f24": [("parental_union", "family_wellbeing", "INCREASES"),
                      ("family_wellbeing", "child_quality", "INCREASES"),
                      ("child_quality", "child_union", "INCREASES")],
 "746bd0b6ca5d1c17": [("predecessor_harm", "expected_disillusion", "INCREASES"),
                      ("expected_disillusion", "current_reverence", "DECREASES"),
                      ("inherited_reverence", "current_reverence", "INCREASES")],
 # -- 11 --
 "c0ea8878c3a341a8": [("misfortune", "need", "INCREASES"),
                      ("need", "help_given", "INCREASES"),
                      ("help_given", "gratitude", "INCREASES"),
                      ("gratitude", "reciprocation", "INCREASES")],
 "e00974d328c4ab98": [("loyalty", "association", "INCREASES"),
                      ("association", "imputed_conduct", "INCREASES"),
                      ("imputed_conduct", "reputation", "DECREASES")],
 "4f7d00fb9c20caa7": [("adversity", "need", "INCREASES"),
                      ("need", "revealed_loyalty", "INCREASES"),
                      ("revealed_loyalty", "retained_friendships", "INCREASES"),
                      ("revealed_loyalty", "false_friendships", "DECREASES")],
 # -- 12 --
 "03ea661ccf0e7b2a": [("dissatisfaction", "staying", "DECREASES"),
                      ("fear_of_unknown", "staying", "INCREASES"),
                      ("familiarity", "staying", "INCREASES")],
 "2ca87deab17939ea": [("need", "searching", "INCREASES"),
                      ("difficulty", "searching", "DECREASES"),
                      ("persistence", "searching", "INCREASES"),
                      ("searching", "finding", "INCREASES")],
 "dcb4ae40420f23a9": [("presumed_impossibility", "effort", "DECREASES"),
                      ("effort", "discovery", "INCREASES")],
 # -- 13 --
 "9ff1d8f15caa6b92": [("grievance", "intent", "INCREASES"),
                      ("simulation", "predicted_loss", "INCREASES"),
                      ("predicted_loss", "intent", "DECREASES")],
 "eaa2f2f29bae35f0": [("grievance", "conflict", "INCREASES"),
                      ("conflict", "fatigue", "INCREASES"),
                      ("fatigue", "conflict", "DECREASES"),
                      ("fatigue", "cooperation", "INCREASES")],
 "6339c6cf046f86b4": [("leadership_change", "redirection", "INCREASES"),
                      ("redirection", "harmful_output", "DECREASES"),
                      ("redirection", "beneficial_output", "INCREASES")],
 # -- 14 --
 "cbb951527590adf0": [("deferral", "savings", "INCREASES"),
                      ("deferral", "living", "DECREASES"),
                      ("time_remaining", "living", "INCREASES"),
                      ("living", "loss", "DECREASES")],
 "c3b48eedd04418e9": [("plan", "progress", "INCREASES"),
                      ("switching", "progress", "DECREASES"),
                      ("progress", "quality", "INCREASES")],
 "0b37681a9815c895": [("procrastination", "missed_deadlines", "INCREASES"),
                      ("missed_deadlines", "threat", "INCREASES"),
                      ("threat", "procrastination", "DECREASES")],
 # -- 15 --
 "87eb5db10105f977": [("disadvantage", "external_skepticism", "INCREASES"),
                      ("external_skepticism", "parental_investment", "DECREASES"),
                      ("parental_investment", "achievement", "INCREASES"),
                      ("achievement", "influence", "INCREASES")],
 "ea202ebbd71ac315": [("obstacle", "access", "DECREASES"),
                      ("charm", "willingness", "INCREASES"),
                      ("willingness", "access", "INCREASES")],
 "6a2dcea6caa89663": [("inherited_wealth", "opportunity", "INCREASES"),
                      ("effort", "merit", "INCREASES"),
                      ("merit", "access", "INCREASES"),
                      ("inherited_wealth", "access", "INCREASES")],
 # -- 16 --  (two repeats of item-11 narratives)
 "c4559fd86e0671c6": [("need", "hospitality", "INCREASES"),
                      ("guest_conduct", "welcome", "INCREASES"),
                      ("duration", "welcome", "DECREASES")],
 "27ad8a5af49b3d4c": [("misfortune", "need", "INCREASES"),
                      ("need", "help_given", "INCREASES"),
                      ("help_given", "gratitude", "INCREASES"),
                      ("gratitude", "reciprocation", "INCREASES")],
 "d877cd319d615969": [("adversity", "need", "INCREASES"),
                      ("need", "revealed_loyalty", "INCREASES"),
                      ("revealed_loyalty", "retained_friendships", "INCREASES"),
                      ("revealed_loyalty", "false_friendships", "DECREASES")],
 # -- 17 --
 "44ac9212033dce83": [("shared_desire", "rivalry", "INCREASES"),
                      ("rivalry", "friendship", "DECREASES"),
                      ("foresight", "withdrawal", "INCREASES"),
                      ("withdrawal", "rivalry", "DECREASES")],
 "81c8851814b43e74": [("shared_desire", "rivalry", "INCREASES"),
                      ("alternatives", "rivalry", "DECREASES"),
                      ("refusal", "alternatives", "DECREASES")],
 "04fb525467449f26": [("party_a_willingness", "affair", "INCREASES"),
                      ("party_b_willingness", "affair", "INCREASES"),
                      ("affair", "blame_on_a", "INCREASES"),
                      ("blame_on_a", "blame_on_b", "DECREASES")],
 # -- 18 --
 "0d2775b24bb7a2a1": [("comparison", "perceived_deficit", "INCREASES"),
                      ("perceived_deficit", "satisfaction", "DECREASES"),
                      ("uniformity", "comparison", "DECREASES")],
 "bebc55f5f7d70c27": [("reticence", "visibility", "DECREASES"),
                      ("request", "visibility", "INCREASES"),
                      ("visibility", "selection", "INCREASES")],
 "15b083a908c68279": [("dissatisfaction", "grievance", "INCREASES"),
                      ("complaint", "redress", "INCREASES"),
                      ("silence", "redress", "DECREASES")],
 # -- 19 --  (4fe3... is the same narrative as 8ea4..., annotated identically)
 "23e23208608642ec": [("separation", "worry", "INCREASES"),
                      ("worry", "own_life", "DECREASES"),
                      ("acceptance", "worry", "DECREASES"),
                      ("acceptance", "own_life", "INCREASES")],
 "4fe3b528107c0984": [("freedom", "partying", "INCREASES"),
                      ("partying", "rest", "DECREASES"),
                      ("rest", "focus", "INCREASES"),
                      ("focus", "grades", "INCREASES")],
 "d7a80e25c5994a7c": [("overthinking", "stress", "INCREASES"),
                      ("advice", "overthinking", "DECREASES"),
                      ("stress", "depression", "INCREASES"),
                      ("depression", "functioning", "DECREASES")],
}
