"""Synthetic worlds with a KNOWN interaction order.

EXP-002 tests F-04, the higher-order remainder. To do that honestly we need
worlds where the true arity of the dependence is not a matter of opinion --
so the outcome is generated by an explicit rule and the rule is the ground
truth. Nothing here is identified by inspection (R-12).

Five binary drivers a..e. Only some matter in any given world; the rest are
present precisely so the statistic has room to find structure that isn't
there.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Callable

VARS = ("a", "b", "c", "d", "e")


@dataclass(frozen=True)
class World:
    name: str
    true_arity: int          # the arity of the dependence actually generated
    drivers: tuple[str, ...]  # which variables participate
    description: str
    rule: Callable[[dict[str, int]], int]
    prepare: Callable[[dict[str, int], random.Random], dict[str, int]] | None = None

    def sample(self, n: int, noise: float, seed: int) -> tuple[list[dict], list[int]]:
        """Draw n independent rows. `noise` flips the outcome with that
        probability -- real measurements are never clean and a statistic that
        only survives noiseless data is not a finding."""
        rng = random.Random(seed)
        rows, ys = [], []
        for _ in range(n):
            row = {v: rng.randint(0, 1) for v in VARS}
            if self.prepare is not None:
                row = self.prepare(row, rng)
            y = self.rule(row)
            if rng.random() < noise:
                y = 1 - y
            rows.append(row)
            ys.append(y)
        return rows, ys


WORLDS: tuple[World, ...] = (
    World("null", 0, (),
          "Y independent of everything. The pure null.",
          lambda r: random.Random(r["a"] * 7 + r["b"] * 13 + r["c"] * 29).randint(0, 1)),

    World("order1", 1, ("a",),
          "Y = a. Single-variable dependence, no interaction at all.",
          lambda r: r["a"]),

    World("order2", 2, ("a", "b"),
          "Y = a XOR b. Pure pairwise: neither variable alone carries any "
          "information, the pair carries all of it.",
          lambda r: r["a"] ^ r["b"]),

    World("order3", 3, ("a", "b", "c"),
          "Y = a XOR b XOR c. Pure three-way: no variable and no PAIR carries "
          "any information. This is the case the whole theory is about.",
          lambda r: r["a"] ^ r["b"] ^ r["c"]),

    World("order3_and", 3, ("a", "b", "c"),
          "Y = a AND b AND c. Three-way, but with pairwise leakage -- subsets "
          "do carry partial signal. The realistic version.",
          lambda r: r["a"] & r["b"] & r["c"]),

    # Filed as a null on first writing, on the reasoning that "majority is
    # just adding things up". That was wrong and the truth table says so:
    # when a != b the outcome is decided ENTIRELY by c. Majority is genuinely
    # synergistic. Reclassified to arity 3 and kept, because the mistake --
    # asserting a property from a name instead of computing it -- is R-12 and
    # deleting the evidence of it would be worse than the mistake.
    World("majority", 3, ("a", "b", "c"),
          "Y = majority(a,b,c). Looks decomposable; isn't. Whenever the first "
          "two disagree, the third decides alone. Genuine three-way structure "
          "wearing an additive-looking name.",
          lambda r: 1 if (r["a"] + r["b"] + r["c"]) >= 2 else 0),

    # The null that `majority` was supposed to be. Three variables all carry
    # information about Y and NONE of it is synergistic -- b and c are just
    # noisy copies of a, so every subset says the same thing with different
    # fidelity. Interaction information should be <= 0 here (redundancy), not
    # positive. This is the case that separates "several participants are
    # involved" from "the configuration does something the parts cannot".
    World("redundant", 1, ("a", "b", "c"),
          "Y = a, with b and c noisy copies of a. Three variables carry "
          "information, all of it redundant, none of it synergistic. THE REAL "
          "NULL for higher-order structure.",
          lambda r: r["a"],
          prepare=lambda r, rng: {**r,
                                  "b": r["a"] if rng.random() < 0.8 else 1 - r["a"],
                                  "c": r["a"] if rng.random() < 0.8 else 1 - r["a"]}),
)


def by_name(name: str) -> World:
    for w in WORLDS:
        if w.name == name:
            return w
    raise KeyError(name)
